backend = "glx";
vsync = true;

shadow = false;
fading = false;
blur-method = "none";

use-damage = true;

corner-radius = 12;

# Enable blur
blur-method = "dual_kawase";
blur-strength = 4;

# Blur background of windows
blur-background = true;

# Blur only when window is NOT focused
blur-background-frame = false;
blur-background-fixed = false;
